const ARTWORKS_DATA = [
  {
    "id": "orbitals-01",
    "collection": "orbitals",
    "title": "Orbit Field",
    "subtitle": "Orbitals 01",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6980.JPEG",
    "link": "./works/orbitals-01-orbit-field.html",
    "sold": false
  },
  {
    "id": "orbitals-02",
    "collection": "orbitals",
    "title": "Blue Structure",
    "subtitle": "Orbitals 02",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6926.JPEG",
    "link": "./works/orbitals-02-blue-structure.html",
    "sold": false
  },
  {
    "id": "orbitals-03",
    "collection": "orbitals",
    "title": "Green Atmosphere",
    "subtitle": "Orbitals 03",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6969.JPEG",
    "link": "./works/orbitals-03-green-atmosphere.html",
    "sold": false
  },
  {
    "id": "orbitals-04",
    "collection": "orbitals",
    "title": "Magenta Signal",
    "subtitle": "Orbitals 04",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_7046.JPEG",
    "link": "./works/orbitals-04-magenta-signal.html",
    "sold": false
  },
  {
    "id": "orbitals-05",
    "collection": "orbitals",
    "title": "Deep Blue Orbit",
    "subtitle": "Orbitals 05",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6925.JPEG",
    "link": "./works/orbitals-05-deep-blue-orbit.html",
    "sold": false
  },
  {
    "id": "orbitals-06",
    "collection": "orbitals",
    "title": "Cosmic Route",
    "subtitle": "Orbitals 06",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6908.JPEG",
    "link": "./works/orbitals-06-cosmic-route.html",
    "sold": false
  },
  {
    "id": "orbitals-07",
    "collection": "orbitals",
    "title": "Violet Gravity",
    "subtitle": "Orbitals 07",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6930.JPEG",
    "link": "./works/orbitals-07-violet-gravity.html",
    "sold": false
  },
  {
    "id": "orbitals-08",
    "collection": "orbitals",
    "title": "Green Core",
    "subtitle": "Orbitals 08",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6976.JPEG",
    "link": "./works/orbitals-08-green-core.html",
    "sold": false
  },
  {
    "id": "orbitals-09",
    "collection": "orbitals",
    "title": "Hidden Garden",
    "subtitle": "Orbitals 09",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6985.JPEG",
    "link": "./works/orbitals-09-hidden-garden.html",
    "sold": false
  },
  {
    "id": "orbitals-10",
    "collection": "orbitals",
    "title": "Urban Bloom",
    "subtitle": "Orbitals 10",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/ORBITALS/IMG_6987.JPEG",
    "link": "./works/orbitals-10-urban-bloom.html",
    "sold": false
  },
  {
    "id": "flow-01",
    "collection": "flow",
    "title": "First Current",
    "subtitle": "Flow 01",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/FLOW/IMG_7726.PNG",
    "link": "./works/flow-01-first-current.html",
    "sold": false
  },
  {
    "id": "flow-02",
    "collection": "flow",
    "title": "Open Movement",
    "subtitle": "Flow 02",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/FLOW/IMG_7727.PNG",
    "link": "./works/flow-02-open-movement.html",
    "sold": false
  },
  {
    "id": "flow-03",
    "collection": "flow",
    "title": "Surface Drift",
    "subtitle": "Flow 03",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/FLOW/IMG_7728.PNG",
    "link": "./works/flow-03-surface-drift.html",
    "sold": false
  },
  {
    "id": "flow-04",
    "collection": "flow",
    "title": "Soft Pulse",
    "subtitle": "Flow 04",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/FLOW/IMG_7734.JPEG",
    "link": "./works/flow-04-soft-pulse.html",
    "sold": false
  },
  {
    "id": "flow-05",
    "collection": "flow",
    "title": "Last Wave",
    "subtitle": "Flow 05",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/FLOW/IMG_7735.JPEG",
    "link": "./works/flow-05-last-wave.html",
    "sold": false
  },
  {
    "id": "deco-01",
    "collection": "deco",
    "title": "Room Accent",
    "subtitle": "Deco 01",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_7708.JPEG",
    "link": "./works/deco-01-room-accent.html",
    "sold": true
  },
  {
    "id": "deco-02",
    "collection": "deco",
    "title": "Wall Rhythm",
    "subtitle": "Deco 02",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_7710.JPEG",
    "link": "./works/deco-02-wall-rhythm.html",
    "sold": false
  },
  {
    "id": "deco-03",
    "collection": "deco",
    "title": "Interior Signal",
    "subtitle": "Deco 03",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_7715.JPEG",
    "link": "./works/deco-03-interior-signal.html",
    "sold": false
  },
  {
    "id": "deco-04",
    "collection": "deco",
    "title": "Modern Layer",
    "subtitle": "Deco 04",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_7716.JPEG",
    "link": "./works/deco-04-modern-layer.html",
    "sold": false
  },
  {
    "id": "deco-05",
    "collection": "deco",
    "title": "Collected Space",
    "subtitle": "Deco 05",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_7721.JPEG",
    "link": "./works/deco-05-collected-space.html",
    "sold": true
  },
  {
    "id": "deco-06",
    "collection": "deco",
    "title": "Structured Chaos",
    "subtitle": "Deco 06",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_8094.JPEG",
    "link": "./works/deco-06-structured-chaos.html",
    "sold": true
  },
  {
    "id": "deco-07",
    "collection": "deco",
    "title": "Industrial Pulse",
    "subtitle": "Deco 07",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_8095.JPEG",
    "link": "./works/deco-07-Industrial-Pulse",
    "sold": false
  },
  {
    "id": "deco-08",
    "collection": "deco",
    "title": "Soft Boundaries",
    "subtitle": "Deco 08",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_8096.JPEG",
    "link": "./works/deco-08-soft-boundaries.html",
    "sold": false
  },
  {
    "id": "deco-09",
    "collection": "deco",
    "title": "Flow State",
    "subtitle": "Deco 09",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_8097.JPEG",
    "link": "./works/deco-09-flow-state.html",
    "sold": false
  },
  {
    "id": "deco-10",
    "collection": "deco",
    "title": "Echo Patterns",
    "subtitle": "Deco 10",
    "medium": "Acrylic on paper",
    "size": "13 × 19 in",
    "image": "./images/DECO/IMG_8098.JPEG",
    "link": "./works/deco-10-echo-patterns.html",
    "sold": false
  },
  {
    "id": "reliefs-01",
    "collection": "reliefs",
    "title": "Orbital Bloom",
    "subtitle": "Reliefs 01",
    "medium": "Resin relief on panel",
    "size": "Estimated dimensions pending",
    "image": "./images/RELIEFS/reliefs-01-orbital-bloom.png",
    "link": "./works/reliefs-01-orbital-bloom.html",
    "sold": false
  },
  {
    "id": "reliefs-02",
    "collection": "reliefs",
    "title": "Agave Signal",
    "subtitle": "Reliefs 02",
    "medium": "Mixed media / acrylic on canvas",
    "size": "Large format · dimensions pending",
    "image": "./images/RELIEFS/reliefs-02-agave-signal.png",
    "link": "./works/reliefs-02-agave-signal.html",
    "sold": false
  },
  {
    "id": "reliefs-03",
    "collection": "reliefs",
    "title": "Fuerza · Visión · Transformación",
    "subtitle": "Reliefs 03 · 2024",
    "medium": "Resin & relief on canvas",
    "size": "Dimensions pending",
    "image": "./images/RELIEFS/reliefs-03-fuerza-vision-transformacion.png",
    "link": "./works/reliefs-03-fuerza-vision-transformacion.html",
    "sold": false
  },
  {
    "id": "reliefs-04",
    "collection": "reliefs",
    "title": "Quiet Surface Diptych",
    "subtitle": "Reliefs 04",
    "medium": "Textured mixed media diptych",
    "size": "Two-piece set · dimensions pending",
    "image": "./images/RELIEFS/reliefs-04-quiet-surface-diptych.png",
    "link": "./works/reliefs-04-quiet-surface-diptych.html",
    "sold": false
  }
];
