const { google } = require('googleapis');
const path = require('path');

// Coloca aquí el ID de tu Google Sheet si ya la creaste vacía,
// o deja el script libre si prefieres que cree un archivo totalmente nuevo.
const SPREADSHEET_ID = "1uY0_p8BCl4Fs-MZMzWWYVdT33_d4BHEI-BVJtS3ednw"; 

const auth = new google.auth.GoogleAuth({
    keyFile: path.join(__dirname, "credentials.json"),
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});
const sheets = google.sheets({ version: "v4", auth });

// Los datos de tu JSON transformados a la estructura de filas
const sheetData = [
    // Fila 1: Encabezados obligatorios para mapear con app.js
    [
        "Series Title", "Code", "Title", "Year", "Technique", "Size", "Image", 
        "Description", "IsAvailable", "Original Price", "Stripe URL", "Prints JSON", 
        "Marketplace Title"
    ],
    // Fila 2 en adelante: Tus obras de arte estructuradas
    ["Orbitals", "JBU-001", "Quantum Drift", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-001.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Quantum Drift | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-003", "Probability Wave", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-003.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "$3,350 MXN", "https://buy.stripe.com/tu_enlace_de_pago_directo", '[{"size":"Tamaño A4","price":"$650 MXN"},{"size":"Tamaño A3","price":"$950 MXN"}]', "Probability Wave | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-004", "Superposition State", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-004.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Superposition State | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-005", "Entangled Memory", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-005.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Entangled Memory | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-006", "Neon Entanglement", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-006.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Neon Entanglement | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-007", "Collapse State", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-007.jpeg", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Collapse State | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-008", "Multiverse Signal", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-008.jpg", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Multiverse Signal | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-009", "Chromatic Resonance", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-009.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Chromatic Resonance | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-010", "Parallel Echo", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-010.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Parallel Echo | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-012", "Memory Fragment", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-012.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Memory Fragment | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-013", "Quantum Bloom", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-013.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Quantum Bloom | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-014", "Consciousness Drift", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-014.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Consciousness Drift | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-015", "Spectral Signal", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-015.jpeg", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Spectral Signal | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-016", "Uncertain Future", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-016.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Uncertain Future | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-017", "Dimensional Echo", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-017.jpeg", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Dimensional Echo | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-018", "Entropic Dream", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-018.jpeg", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Entropic Dream | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-019", "Resonance Field", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-019.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Resonance Field | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-020", "Neural Universe", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-020.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Neural Universe | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-021", "Temporal Fragment", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-021.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Temporal Fragment | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-022", "Particle Memory", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-022.PNG", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Particle Memory | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-023", "Frequency Shift", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-023.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Frequency Shift | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-024", "Electric Consciousness", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-024.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Electric Consciousness | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-026", "Cosmic Interference", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-026.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Cosmic Interference | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-027", "Infinite Probability", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-027.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Infinite Probability | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-028", "Quantum Orbit", "2026", "Acrylic on Paper", "13 x 19 in", "assets/artworks/JBU-028.png", "A translucent being suspended within concentric orbital fields. Layers of blue, violet, and black suggest invisible forces, memory traces, and energetic pathways surrounding the figure.", "TRUE", "", "", "[]", ""],
    ["Orbitals", "JBU-029", "Crimson Signal", "2026", "Acrylic on Paper", "13 x 19 in", "assets/artworks/JBU-029.png", "A variation of The Translucent Being emerging through crimson geometric bursts and fragmented structures. The composition explores contrast between organic presence and constructed reality.", "TRUE", "", "", "[]", ""],
    ["Orbitals", "JBU-041", "Solar Nexus", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-041.png", "Una composición cargada de energía cósmica donde líneas de fuerza doradas irradian desde un núcleo místico. La superposición de tonos violetas, azules y ocres evoca la colisión de partículas y la calidez de un sol abstracto.", "TRUE", "", "", "[]", "Solar Nexus | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-042", "Monochrome Totem", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-042.png", "Exploración de la identidad contemporánea y la cultura pop a través de una silueta totémica rodeada de trazos caóticos en amarillo, rojo y gris. Las texturas de patrones tramados contrastan con la espontaneidad del fondo gestual.", "TRUE", "", "", "[]", "Monochrome Totem | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Orbitals", "JBU-043", "Neon Eclipse", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-043.png", "Una pieza magnética que enmarca una figura icónica en un halo rosa eléctrico de alto contraste. El fondo de texturas densas en verde oliva y negro se entrelaza con órbitas lineales que sugieren campos de fuerza y magnetismo invisible.", "TRUE", "", "", "[]", "Neon Eclipse | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Identidades y Raíces", "JBU-030", "El Hombre de la Sandía", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-030.png", "Retrato de tintes nostálgicos y vivos contrastes que rinde homenaje a la iconografía de la tierra y los frutos locales.", "TRUE", "", "", "[]", "El Hombre de la Sandía | Obra Original Firmada | Expresionismo Mexicano | Marco Incluido"],
    ["Identidades y Raíces", "JBU-031", "Mirada Fragmentada", "2026", "Óleo pastel y acrílico sobre papel", "Por definir", "assets/artworks/JBU-031.png", "Estudio del rostro humano a través de la descomposición formal, realzando la mirada y los matices cromáticos primarios.", "TRUE", "", "", "[]", "Mirada Fragmentada | Obra Original Firmada | Retrato Cubista | Marco Incluido"],
    ["Identidades y Raíces", "JBU-032", "Quantum Drift", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-032.png", "Obra original de Josue Beltran Uresti perteneciente a una serie inspirada en la física cuántica, la memoria y la percepción.", "TRUE", "", "", "[]", "Quantum Drift | Obra Original Firmada | Arte Contemporáneo | Marco Incluido"],
    ["Identidades y Raíces", "JBU-033", "Cinética del Caos", "2026", "Pastel y técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-033.png", "Composición de gran dinamismo que explora las fuerzas vectoriales, el movement animal y las órbitas de energía desbocada.", "TRUE", "", "", "[]", "Cinética del Caos | Obra Original Firmada | Arte Expresionista | Marco Incluido"],
    ["Identidades y Raíces", "JBU-034", "La Silla del Cantor", "2026", "Técnica mixta sobre papel", "16 * 20 pulgadas", "assets/artworks/JBU-034.png", "Representación cubista de dos personajes entrelazados en un entorno interior, jugando con las líneas rectas y los planos cromáticos contrastantes.", "TRUE", "", "", "[]", "La Silla del Cantor | Obra Original Firmada | Cubismo Contemporáneo | Marco Incluido"],
    ["Identidades y Raíces", "JBU-035", "Teatro del Cotidiano", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-035.png", "Escena multifigurativa que evoca la interacción de personajes tras un balcón o ventana, distorsionando la profundidad espacial.", "TRUE", "", "", "[]", "Teatro del Cotidiano | Obra Original Firmada | Abstracción Figurada | Marco Incluido"],
    ["Tótems Urbanos", "JBU-036", "Neon Idol", "2026", "Técnica mixta y acrílico sobre papel", "Por definir", "assets/artworks/JBU-036.png", "Silueta icónica envuelta en vibrantes tonos cálidos sobre un fondo azul eléctrico, explorando la saturación y el trazo gestual urbano.", "TRUE", "", "", "[]", "Neon Idol | Obra Original Firmada | Neoexpresionismo Pop | Marco Incluido"],
    ["Tótems Urbanos", "JBU-037", "Shadow Companion", "2026", "Técnica mixta y acrílico sobre papel", "Por definir", "assets/artworks/JBU-037.png", "Una figura central oscura y misteriosa delimitada por trazos enérgicos de color rosa, entablando un diálogo entre la cultura pop y la abstracción.", "TRUE", "", "", "[]", "Shadow Companion | Obra Original Firmada | Arte Urbano Contemporáneo | Marco Incluido"],
    ["Tótems Urbanos", "JBU-038", "Vórtice Lúdico", "2026", "Técnica mixta y acrílico sobre papel", "Por definir", "assets/artworks/JBU-038.png", "Estudio de color y movimiento donde espirales violetas enmarcan una silueta encendida en rojos y amarillos, capturando la energía del objeto de culto.", "TRUE", "", "", "[]", "Vórtice Lúdico | Obra Original Firmada | Expresionismo Abstracto | Marco Incluido"],
    ["Tótems Urbanos", "JBU-039", "Ascensión Gráfica", "2026", "Técnica mixta y pastel sobre papel", "Por definir", "assets/artworks/JBU-039.png", "Líneas angulares y flechas que simulan el dinamismo de las calles rodean a una figura central enigmática de tonos olivas y dorados.", "TRUE", "", "", "[]", "Ascensión Gráfica | Obra Original Firmada | Street Art Fine Art | Marco Incluido"],
    ["Tótems Urbanos", "JBU-040", "Reliquia Pop", "2026", "Técnica mixta y collage sobre papel", "Por definir", "assets/artworks/JBU-040.png", "Pieza de gran textura y capas superpuestas que evocan el desgaste de los muros urbanos frente a la permanencia de la iconografía moderna.", "TRUE", "", "", "[]", "Reliquia Pop | Obra Original Firmada | Arte Matérico Contemporáneo | Marco Incluido"],
    ["Skulls", "JBU-002", "Vortex Skull", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-002.png", "Una pieza de gran dinamismo donde una calavera central queda envuelta en un torbellino de líneas radiales oscuras y un fondo texturizado en tonos rosas, violetas y verdes.", "TRUE", "", "", "[]", "Vortex Skull | Obra Original Firmada | Serie Skulls | Marco Incluido"],
    ["Skulls", "JBU-011", "Orbital Skull", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-011.png", "Exploración gestual donde anillos orbitales de color naranja encendido delimitan una calavera texturizada, suspendida sobre un fondo oscuro salpicado de trazos expresivos y destellos de color.", "TRUE", "", "", "[]", "Orbital Skull | Obra Original Firmada | Serie Skulls | Marco Incluido"],
    ["Skulls", "JBU-025", "Helios Skull", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-025.png", "Una calavera abstracta de cuencas encendidas emerge en el centro de una corona solar de trazos naranjas y amarillos. El fondo en lavanda y verde aporta una atmósfera mística y ceremonial.", "TRUE", "", "", "[]", "Helios Skull | Obra Original Firmada | Serie Skulls | Marco Incluido"],
    ["Skulls", "JBU-041", "Solar Nexus Skull", "2026", "Técnica mixta sobre papel", "Por definir", "assets/artworks/JBU-041.png", "Una composición cargada de energía cósmica donde líneas de fuerza doradas irradian desde una calavera mística central. La superposición de tonos violetas, azules y ocres evoca la calidez de un sol abstracto.", "TRUE", "", "", "[]", "Solar Nexus Skull | Obra Original Firmada | Serie Skulls | Marco Incluido"]
];

async function populateSheet() {
    try {
        console.log("⏳ Subiendo catálogo a Google Sheets...");
        
        await sheets.spreadsheets.values.update({
            spreadsheetId: SPREADSHEET_ID,
            range: "Catalogo!A1", // Nombre de la hoja y celda inicial
            valueInputOption: "RAW",
            requestBody: {
                values: sheetData
            }
        });

        console.log("✅ ¡Hoja de cálculo generada y poblada con éxito con tus 44 obras!");
    } catch (error) {
        console.error("❌ Error al interactuar con Google Sheets API:", error);
    }
}

populateSheet();